on:
  push:
    branches: [main]
    paths:
      - "recipes/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "recipes/**"
      - ".github/workflows/**"

  workflow_dispatch:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build "rich" conda package
        uses: prefix-dev/rattler-build-action@main
        with:
          recipe-path: ./recipes/rich/recipe.yaml
          upload-artifact: false
      - name: Build "curl" conda package
        uses: prefix-dev/rattler-build-action@main
        with:
          recipe-path: ./recipes/curl/recipe.yaml
          upload-artifact: false

    