on:
  push:
    branches: [main]
    paths:
      - "recipes/**"
  pull_request:
    paths:
      - "recipes/**"

  workflow_dispatch:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.1.1
        with:
          recipe-path: ./recipes/rich/recipe.yaml
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.1.1
        with:
          recipe-path: ./recipes/curl/recipe.yaml

    